# Generated by Django 6.0.2 on 2026-02-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMasters',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category_msters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeptMasters',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('userid', models.IntegerField()),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('createAT', models.DateTimeField(db_column='createat')),
                ('updateAT', models.DateTimeField(db_column='updateat')),
            ],
            options={
                'db_table': 'dept_masters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationMasters',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('did', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('createAT', models.DateTimeField(db_column='createat')),
                ('updateAT', models.DateTimeField(db_column='updateat')),
            ],
            options={
                'db_table': 'location_masters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImageMasters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('create_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'productimage_masters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductMasters',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('dimensions', models.CharField(max_length=100, null=True)),
                ('cid', models.IntegerField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('did', models.IntegerField()),
                ('createat', models.DateTimeField()),
                ('updateat', models.DateTimeField()),
            ],
            options={
                'db_table': 'product_masters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StorageMasters',
            fields=[
                ('storageid', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.IntegerField()),
                ('lid', models.IntegerField()),
                ('did', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('createat', models.DateTimeField()),
                ('updateat', models.DateTimeField()),
            ],
            options={
                'db_table': 'storage_masters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMasters',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_masters',
            },
        ),
    ]
