# Generated by Django 6.0.2 on 2026-02-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymasters',
            options={},
        ),
        migrations.AlterModelOptions(
            name='deptmasters',
            options={},
        ),
        migrations.AlterModelOptions(
            name='locationmasters',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productimagemasters',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productmasters',
            options={},
        ),
        migrations.AlterModelOptions(
            name='storagemasters',
            options={},
        ),
    ]
